import { useLocation,useNavigate } from "react-router-dom";
import { FaHeartbeat,FaTint,FaDownload,FaArrowLeft } from "react-icons/fa";
import { useEffect } from "react";

export default function DoctorFinalReport(){

const location=useLocation();
const navigate=useNavigate();

const report=
location.state||
JSON.parse(
localStorage.getItem(
"latestReport"
)
);

useEffect(()=>{

if(!report)
return;

localStorage.setItem(
"latestReport",
JSON.stringify(report)
);

const old=
JSON.parse(
localStorage.getItem(
"prescriptions"
)
)||[];


const exists=
old.some(

(item)=>

item.date===report.date&&
item.symptoms===report.symptoms

);


if(!exists){

const updated=[

...old,

{
...report,
date:new Date().toLocaleDateString()
}

];


localStorage.setItem(
"prescriptions",
JSON.stringify(updated)
);

}

},[report]);



if(!report){

return(

<div className="min-h-screen flex justify-center items-center">

No Report Found

</div>

);

}



const {
name,
symptoms,
risk,
diagnosis,
prescription,
recommendation,
followUp,
notes,
heartRate,
bp,
oxygen

}=report;



return(

<div className="min-h-screen bg-[#eef4f7] pt-[90px] sm:pt-[100px] md:pt-[90px] px-4 pb-8">

<div className="max-w-[1000px] mx-auto bg-white rounded-3xl shadow-xl overflow-hidden">

{/* HEADER */}

<div className="flex justify-between items-center gap-3 px-4 sm:px-8 py-5 border-b">

<button onClick={()=>navigate(-1)}>

<FaArrowLeft/>

</button>


<button className="bg-teal-500 text-white px-4 py-2 rounded-xl flex items-center gap-2 text-sm">

Download

<FaDownload/>

</button>

</div>




{/* TITLE */}

<div className="px-4 sm:px-8 py-6">

<h1 className="text-2xl sm:text-4xl font-bold">

Clinical Report

</h1>


<p className="text-gray-500 mt-2 text-sm sm:text-base">

Generated by Doctor + AI

</p>

</div>




{/* PATIENT */}

<div className="grid grid-cols-1 md:grid-cols-2 border-t">

<div className="p-5 sm:p-6">

<img
src="https://i.pravatar.cc/80"
className="w-20 h-20 rounded-full"
/>


<h2 className="mt-4 text-lg sm:text-xl font-semibold">

{name||"Patient"}

</h2>


<p>
Risk:
{" "}
{risk}
</p>


<p className="break-words">

Symptoms:
{" "}
{symptoms}

</p>


</div>




<div className="p-5 sm:p-6 space-y-3">

<p className="flex gap-2 items-center">

<FaHeartbeat/>

{heartRate||"N/A"} bpm

</p>


<p>

BP:
{" "}
{bp||"N/A"}

</p>


<p className="flex gap-2 items-center">

<FaTint/>

{oxygen||"N/A"} %

</p>

</div>

</div>





{/* AI */}

<div className="px-4 sm:px-8 py-6">

<div className="bg-[#f8fafb] rounded-xl p-5 sm:p-6">

<h2 className="font-semibold">

AI Assessment

</h2>


<p className="text-red-500 text-xl sm:text-2xl mt-2">

{risk}

</p>

</div>

</div>





{/* REPORT */}

<div className="px-4 sm:px-8 pb-8">

<div className="bg-[#f8fafb] rounded-xl p-5 sm:p-8 space-y-5">

<div>

<h4 className="font-semibold">

Diagnosis

</h4>

<p>
{diagnosis}
</p>

</div>



<div>

<h4 className="font-semibold">

Recommendation

</h4>

<p>
{recommendation}
</p>

</div>



<div>

<h4 className="font-semibold">

Medicine

</h4>

<p>
{prescription}
</p>

</div>



<div>

<h4 className="font-semibold">

Follow Up

</h4>

<p>
{followUp}
</p>

</div>



<div>

<h4 className="font-semibold">

Doctor Notes

</h4>

<p>
{notes}
</p>

</div>





<div className="border-t pt-6 flex flex-col sm:flex-row justify-between gap-4">

<div>

<p>

Dr Singh

</p>


<p className="text-sm text-gray-500">

Cardiologist

</p>

</div>


<div>

Signature ✔

</div>

</div>


</div>

</div>


</div>

</div>

);

}